// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUKjQquX4Zf6zyoGFgTZ_nzq1G4rB4mtw',
    appId: '1:830910239523:web:bfe9db7306fdbe38a93296',
    messagingSenderId: '830910239523',
    projectId: 'firebase-in-flutter',
    authDomain: 'fir-in-flutter-9e8ef.firebaseapp.com',
    storageBucket: 'firebase-in-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAADeA2WT0CzCdP-I7wiBghQy84dvu5sf0',
    appId: '1:830910239523:android:188f6a5a6f1dda1ca93296',
    messagingSenderId: '830910239523',
    projectId: 'firebase-in-flutter',
    storageBucket: 'firebase-in-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaofxtZtmlgLXU4-PLUG3ILFCOHJXWepU',
    appId: '1:830910239523:ios:84ac33e784413266a93296',
    messagingSenderId: '830910239523',
    projectId: 'firebase-in-flutter',
    storageBucket: 'firebase-in-flutter.appspot.com',
    iosBundleId: 'com.example.firebaseInFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaofxtZtmlgLXU4-PLUG3ILFCOHJXWepU',
    appId: '1:830910239523:ios:3dba8550966a3ebda93296',
    messagingSenderId: '830910239523',
    projectId: 'firebase-in-flutter',
    storageBucket: 'firebase-in-flutter.appspot.com',
    iosBundleId: 'com.example.firebaseInFlutter.RunnerTests',
  );
}
